# name: Docz

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build Docz
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # Setup .npmrc file to publish to npm
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'
#           registry-url: 'https://registry.npmjs.org'
#       - run: yarn add docz
#       - run: yarn docz:build
